<html>
<head>
<title>Introduction error handling in Python</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">Python 中的错误处理简介</h1>
<blockquote>原文：<a href="https://blog.devgenius.io/introduction-error-handling-in-python-1dac7c026456?source=collection_archive---------12-----------------------#2022-03-25">https://blog.devgenius.io/introduction-error-handling-in-python-1dac7c026456?source=collection_archive---------12-----------------------#2022-03-25</a></blockquote><div><div class="fc ib ic id ie if"/><div class="ig ih ii ij ik"><div class=""/><div class=""><h2 id="c841" class="pw-subtitle-paragraph jk im in bd b jl jm jn jo jp jq jr js jt ju jv jw jx jy jz ka kb dk translated">错误处理的深入介绍</h2></div><h2 id="a5be" class="kc kd in bd ke kf kg dn kh ki kj dp kk kl km kn ko kp kq kr ks kt ku kv kw kx bi translated">介绍</h2><p id="13af" class="pw-post-body-paragraph ky kz in la b lb lc jo ld le lf jr lg kl lh li lj kp lk ll lm kt ln lo lp lq ig bi translated">如果你一直在用 Python 编程，你可能会遇到一些导致你的程序停止运行的错误。错误通常被称为 bug，调试是识别和纠正代码中错误的过程。Python 有两种类型的错误——语法错误和异常。本教程将向您介绍 Python 中两种不同的错误以及如何处理它们。您将学习识别和调试语法错误。您还将了解异常、<em class="lr"> try-except </em>语句以及<em class="lr"> else </em>和<em class="lr"> finally </em>子句。</p><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div role="button" tabindex="0" class="ly lz di ma bf mb"><div class="gh gi ls"><img src="../Images/12d311086fcadd94bcf32bb43e6c481f.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*QimnT9rDTBQGZ4V0h-_9cg.jpeg"/></div></div><figcaption class="me mf gj gh gi mg mh bd b be z dk translated">照片由<a class="ae mi" href="https://unsplash.com/@cookiethepom?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText" rel="noopener ugc nofollow" target="_blank"> Cookie 在<a class="ae mi" href="https://unsplash.com/s/photos/error?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上的 Pom </a>拍摄</figcaption></figure><h2 id="6969" class="kc kd in bd ke kf kg dn kh ki kj dp kk kl km kn ko kp kq kr ks kt ku kv kw kx bi translated">语法错误</h2><p id="3422" class="pw-post-body-paragraph ky kz in la b lb lc jo ld le lf jr lg kl lh li lj kp lk ll lm kt ln lo lp lq ig bi translated">也被称为<em class="lr">解析错误</em>，语法错误是您在使用 Python 时会遇到的最常见的一种错误。当您没有使用 Python 语言的正确结构时，就会出现这种情况。换句话说，语法错误是由代码中的错误引起的。常见的语法错误包括:</p><ul class=""><li id="f84a" class="mj mk in la b lb ml le mm kl mn kp mo kt mp lq mq mr ms mt bi translated">不正确的缩进，</li><li id="d004" class="mj mk in la b lb mu le mv kl mw kp mx kt my lq mq mr ms mt bi translated">忘记了 if 语句中的冒号，</li><li id="0e64" class="mj mk in la b lb mu le mv kl mw kp mx kt my lq mq mr ms mt bi translated">忘记了右括号，</li><li id="db57" class="mj mk in la b lb mu le mv kl mw kp mx kt my lq mq mr ms mt bi translated">拼错一个关键词，以及</li><li id="ace7" class="mj mk in la b lb mu le mv kl mw kp mx kt my lq mq mr ms mt bi translated">将关键字放在错误的位置。</li></ul><p id="ba65" class="pw-post-body-paragraph ky kz in la b lb ml jo ld le mm jr lg kl mz li lj kp na ll lm kt nb lo lp lq ig bi translated">我们来看几个例子。在你最喜欢的代码编辑器中尝试它们，看看你是否能修复它们。</p><pre class="lt lu lv lw gt nc nd ne nf aw ng bi"><span id="2677" class="kc kd in nd b gy nh ni l nj nk"># 1. syntax error in print statement <br/>print("Hello world!) </span><span id="3647" class="kc kd in nd b gy nl ni l nj nk"><strong class="nd io">#output </strong><br/> print("Hello world!)<br/>          ^<br/>SyntaxError: unterminated string literal (detected at line 2)</span></pre><p id="5c2d" class="pw-post-body-paragraph ky kz in la b lb ml jo ld le mm jr lg kl mz li lj kp na ll lm kt nb lo lp lq ig bi translated">在上面的代码中，你会注意到我们忘记了右引号，导致了语法错误。让我们再看一个例子。</p><pre class="lt lu lv lw gt nc nd ne nf aw ng bi"><span id="3e35" class="kc kd in nd b gy nh ni l nj nk">num = 0<br/>if num &lt; 3<br/>    print("Number is less than 3.")<br/>else:<br/>    print("Number is greater than 3.") </span><span id="4575" class="kc kd in nd b gy nl ni l nj nk"><strong class="nd io">#output<br/></strong> File "C:\Users\....\PycharmProjects\pythonFundamentals\syntaxError.py", line 3<br/>    if num &lt; 3<br/>              ^<br/>SyntaxError: expected ':'</span></pre><p id="5670" class="pw-post-body-paragraph ky kz in la b lb ml jo ld le mm jr lg kl mz li lj kp na ll lm kt nb lo lp lq ig bi translated">在上面的代码中，我们“不小心”在 if 语句中省略了一个冒号，导致了一个错误。</p><p id="8ecc" class="pw-post-body-paragraph ky kz in la b lb ml jo ld le mm jr lg kl mz li lj kp na ll lm kt nb lo lp lq ig bi translated">正如您在上面的例子中看到的，语法错误相对容易修复。Python 会告诉你是什么导致了错误，并给出错误发生的行号。这使得解决语法错误变得很容易，通过更多的 Python 编程实践，您将会提高这一技能。</p><h2 id="dee3" class="kc kd in bd ke kf kg dn kh ki kj dp kk kl km kn ko kp kq kr ks kt ku kv kw kx bi translated">例外</h2><p id="c771" class="pw-post-body-paragraph ky kz in la b lb lc jo ld le lf jr lg kl lh li lj kp lk ll lm kt ln lo lp lq ig bi translated">第二种错误是运行时错误<em class="lr"/>。在这种情况下，程序的语法是正确的，但是在其中一个语句的执行过程中出现了错误，导致解释器停止执行程序。异常在程序被解析时不会被检测到，只有在运行时导致程序停止时才会被检测到。当 python 程序引发异常时，会创建一个异常对象。如果您的代码不处理此异常，您的程序将会停止。</p><p id="94d8" class="pw-post-body-paragraph ky kz in la b lb ml jo ld le mm jr lg kl mz li lj kp na ll lm kt nb lo lp lq ig bi translated">有各种类型的异常和 python，包括以下常见示例:</p><ol class=""><li id="959b" class="mj mk in la b lb ml le mm kl mn kp mo kt mp lq nm mr ms mt bi translated"><strong class="la io">除以零</strong></li></ol><p id="e6e0" class="pw-post-body-paragraph ky kz in la b lb ml jo ld le mm jr lg kl mz li lj kp na ll lm kt nb lo lp lq ig bi translated">当分母为零时，也就是当你试图将一个数除以零时，就会出现这种情况。</p><pre class="lt lu lv lw gt nc nd ne nf aw ng bi"><span id="ef4a" class="kc kd in nd b gy nh ni l nj nk">#devision by zero <br/>a = 20/0 <br/>print(a)</span></pre><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div role="button" tabindex="0" class="ly lz di ma bf mb"><div class="gh gi nn"><img src="../Images/9b4aba2b7103599bb0cf39b101ada52f.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*j_hUCPLcZsYzu3W5mZozVQ.png"/></div></div><figcaption class="me mf gj gh gi mg mh bd b be z dk translated">除以零误差示例</figcaption></figure><p id="0dd5" class="pw-post-body-paragraph ky kz in la b lb ml jo ld le mm jr lg kl mz li lj kp na ll lm kt nb lo lp lq ig bi translated"><strong class="la io"> 2。名称错误</strong></p><p id="7abd" class="pw-post-body-paragraph ky kz in la b lb ml jo ld le mm jr lg kl mz li lj kp na ll lm kt nb lo lp lq ig bi translated">当您拼错变量名或试图在声明变量之前使用它时，会出现此错误。</p><pre class="lt lu lv lw gt nc nd ne nf aw ng bi"><span id="9e4e" class="kc kd in nd b gy nh ni l nj nk">#Name error <br/>a = 20<br/>b = 30<br/>print( a + c)</span></pre><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div role="button" tabindex="0" class="ly lz di ma bf mb"><div class="gh gi no"><img src="../Images/bb0e0864b84067f1a5b182f487e3e561.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*k3KbGZqpHSUuWNMBWLc2dg.png"/></div></div><figcaption class="me mf gj gh gi mg mh bd b be z dk translated">名称错误示例</figcaption></figure><p id="cc6d" class="pw-post-body-paragraph ky kz in la b lb ml jo ld le mm jr lg kl mz li lj kp na ll lm kt nb lo lp lq ig bi translated"><strong class="la io"> 3。类型错误</strong></p><p id="758e" class="pw-post-body-paragraph ky kz in la b lb ml jo ld le mm jr lg kl mz li lj kp na ll lm kt nb lo lp lq ig bi translated">当对错误的数据类型执行算术运算时，会出现这种情况。</p><pre class="lt lu lv lw gt nc nd ne nf aw ng bi"><span id="88a6" class="kc kd in nd b gy nh ni l nj nk">#type error <br/>a = 20<br/>b = "Python"<br/>print( a + b)</span></pre><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div role="button" tabindex="0" class="ly lz di ma bf mb"><div class="gh gi no"><img src="../Images/8a90a823d9d427362eb0a2fdcae387a6.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*jDGca-tlHgHLrobsGplOaw.png"/></div></div><figcaption class="me mf gj gh gi mg mh bd b be z dk translated">类型错误示例</figcaption></figure><p id="b989" class="pw-post-body-paragraph ky kz in la b lb ml jo ld le mm jr lg kl mz li lj kp na ll lm kt nb lo lp lq ig bi translated">Python 有几个内置的异常，你可以在这里查看<a class="ae mi" href="https://docs.python.org/3/library/exceptions.html#bltin-exceptions" rel="noopener ugc nofollow" target="_blank"/>。</p><h2 id="c015" class="kc kd in bd ke kf kg dn kh ki kj dp kk kl km kn ko kp kq kr ks kt ku kv kw kx bi translated">处理异常</h2><p id="03bc" class="pw-post-body-paragraph ky kz in la b lb lc jo ld le lf jr lg kl lh li lj kp lk ll lm kt ln lo lp lq ig bi translated">我们可以使用 Python 中的 try-except 块来捕获和处理异常。这遵循以下逻辑:</p><pre class="lt lu lv lw gt nc nd ne nf aw ng bi"><span id="363f" class="kc kd in nd b gy nh ni l nj nk">try:<br/>   run this code <br/>except:<br/>   run this code if there is an exeption </span></pre><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div class="gh gi np"><img src="../Images/f7ce7a269457672ff4ce47cddea3eda6.png" data-original-src="https://miro.medium.com/v2/resize:fit:1328/format:webp/0*liy9fkhxf-LEeTEC.png"/></div><figcaption class="me mf gj gh gi mg mh bd b be z dk translated">尝试和 except 块语法。来源<a class="ae mi" href="https://www.learnbyexample.org/python-exceptions-try-except/" rel="noopener ugc nofollow" target="_blank">以身作则</a></figcaption></figure><p id="dbbe" class="pw-post-body-paragraph ky kz in la b lb ml jo ld le mm jr lg kl mz li lj kp na ll lm kt nb lo lp lq ig bi translated">作为程序的正常部分，try 块在 except 块之前执行。但是，如果在执行过程中出现错误，将跳过块的其余部分，Python 将执行 except 块。简而言之，except 代码定义了如何处理异常。异常处理的一个简单例子是用户试图被零除的情况。让我们使用 try 和 except 块修改前面的代码。</p><pre class="lt lu lv lw gt nc nd ne nf aw ng bi"><span id="c1f4" class="kc kd in nd b gy nh ni l nj nk"># division by zero exception handling<br/><br/>try:<br/>    100 / 0<br/>except:<br/>    print("You cannot divide by zero.")<br/><br/>print("Program executed successfully")</span></pre><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div role="button" tabindex="0" class="ly lz di ma bf mb"><div class="gh gi nq"><img src="../Images/2be79b1f7d9fa2a582eb1d686b34cb23.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*_9fIyUIij4F9DDldrUvnCg.png"/></div></div><figcaption class="me mf gj gh gi mg mh bd b be z dk translated">被零除错误处理示例</figcaption></figure><p id="5f00" class="pw-post-body-paragraph ky kz in la b lb ml jo ld le mm jr lg kl mz li lj kp na ll lm kt nb lo lp lq ig bi translated">请注意程序是如何继续运行并打印“程序执行成功”消息的，即使它遇到了被零除的错误。这是因为我们用 except 块处理了异常，防止程序崩溃。</p><p id="c1db" class="pw-post-body-paragraph ky kz in la b lb ml jo ld le mm jr lg kl mz li lj kp na ll lm kt nb lo lp lq ig bi translated">即使我们捕获了被零除的异常，我们当前的代码也会为所有其他异常打印相同的消息。例如，尝试将零改为字符串，看看会发生什么。Python 允许您定义尽可能多的异常，并在 except 语句中指定它们。这与我们之前捕捉所有异常的代码形成了对比。让我们修改代码来指定我们想要捕捉的错误类型。</p><pre class="lt lu lv lw gt nc nd ne nf aw ng bi"><span id="6ea7" class="kc kd in nd b gy nh ni l nj nk"># division by zero exception handling<br/><br/>try:<br/>    100 / "game"<br/>except ZeroDivisionError:<br/>    print("You cannot divide by zero.")<br/>except:<br/>    print("Encountered a different error")</span></pre><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div role="button" tabindex="0" class="ly lz di ma bf mb"><div class="gh gi nq"><img src="../Images/9982e732ce35460b0be7a4ce9cd601b6.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*SJ49hE5oiZkMw6mCMoDAwA.png"/></div></div></figure><p id="1288" class="pw-post-body-paragraph ky kz in la b lb ml jo ld le mm jr lg kl mz li lj kp na ll lm kt nb lo lp lq ig bi translated">在上面的代码中，第二个异常处理其他类型的错误，包括因试图用字符串进行除法运算而导致的 TypeError。通过在 except 块中将多个异常指定为元组，也可以为多个异常执行相同的代码块。</p><pre class="lt lu lv lw gt nc nd ne nf aw ng bi"><span id="ef9e" class="kc kd in nd b gy nh ni l nj nk"># division by zero exception handling<br/><br/>try:<br/>    100 / "game"<br/>except (ZeroDivisionError, TypeError):<br/>    print("You cannot divide by zero or a string")<br/>except:<br/>    print("Encountered a different error")</span></pre><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div role="button" tabindex="0" class="ly lz di ma bf mb"><div class="gh gi nq"><img src="../Images/6fdcf1925b408f57ce8a6d6f77085243.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*By1hM94QmeTbMzXb-o4zfQ.png"/></div></div><figcaption class="me mf gj gh gi mg mh bd b be z dk translated">多个异常处理示例</figcaption></figure><h2 id="af2e" class="kc kd in bd ke kf kg dn kh ki kj dp kk kl km kn ko kp kq kr ks kt ku kv kw kx bi translated">Else 和 finally 子句</h2><p id="1153" class="pw-post-body-paragraph ky kz in la b lb lc jo ld le lf jr lg kl lh li lj kp lk ll lm kt ln lo lp lq ig bi translated">try 和 except 块有两个可选子句，即 else 和 finally 子句。只有在没有引发异常时，才会执行 else 子句。如果存在异常，它不会执行。让我们试一试，看看效果如何。</p><pre class="lt lu lv lw gt nc nd ne nf aw ng bi"><span id="2243" class="kc kd in nd b gy nh ni l nj nk"># division by zero exception handling<br/><br/>try:<br/>    100 / 2<br/>except (ZeroDivisionError, TypeError):<br/>    print("You cannot divide by zero or a string")<br/>else:<br/>    print("No errors encountered.")</span></pre><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div role="button" tabindex="0" class="ly lz di ma bf mb"><div class="gh gi nq"><img src="../Images/ebf08689f5efa8f8c3c97049310649c3.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*ocN2oQvZJ877hrwgS0nKBQ.png"/></div></div></figure><p id="8b7d" class="pw-post-body-paragraph ky kz in la b lb ml jo ld le mm jr lg kl mz li lj kp na ll lm kt nb lo lp lq ig bi translated">最后，我们可以使用可选的 Finally 子句(没有双关的意思),无论异常是否发生，该子句都会被执行。</p><pre class="lt lu lv lw gt nc nd ne nf aw ng bi"><span id="e57d" class="kc kd in nd b gy nh ni l nj nk"># division by zero exception handling<br/><br/>try:<br/>    100 / 0<br/>except (ZeroDivisionError, TypeError):<br/>    print("You cannot divide by zero or a string")<br/>else:<br/>    print("No errors encountered.")<br/><br/>finally:<br/>    print("This will always execute")</span></pre><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div role="button" tabindex="0" class="ly lz di ma bf mb"><div class="gh gi nq"><img src="../Images/b5ba4de6c6e712762c23653e8993220b.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*dx4Kkqlg6QgqZA_CONUJ5w.png"/></div></div></figure><p id="d4fc" class="pw-post-body-paragraph ky kz in la b lb ml jo ld le mm jr lg kl mz li lj kp na ll lm kt nb lo lp lq ig bi translated">finally 子句通常用于执行清理操作，不管在什么情况下都应该执行这些操作。例子包括清理一些资源或关闭一个文件。</p><h2 id="6496" class="kc kd in bd ke kf kg dn kh ki kj dp kk kl km kn ko kp kq kr ks kt ku kv kw kx bi translated">总结一下</h2><p id="fd6e" class="pw-post-body-paragraph ky kz in la b lb lc jo ld le lf jr lg kl lh li lj kp lk ll lm kt ln lo lp lq ig bi translated">我们现在已经结束了关于处理 python 错误的介绍性教程。在本教程中，您了解了语法错误以及如何纠正它们。您还了解了异常以及它们与语法错误的区别。最后，您学习了如何使用 try-except 块来处理 python 中的错误。我希望你发现教程内容丰富，并将继续练习和提高你的 python 技能。</p></div></div>    
</body>
</html>